# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - YourStreet

on:
push:
branches:
- main
workflow_dispatch:

env:
PROJECT_PATH: ./backend

jobs:
build:
runs-on: windows-latest
permissions:
contents: read

steps:
  - uses: actions/checkout@v4

  - name: Set up .NET
    uses: actions/setup-dotnet@v4
    with:
      dotnet-version: '9.x'

  - name: Restore
    run: dotnet restore ${{ env.PROJECT_PATH }}

  - name: Build
    run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

  - name: Publish
    run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -o ${{env.DOTNET_ROOT}}/myapp --no-build

  - name: Upload artifact for deployment
    uses: actions/upload-artifact@v4
    with:
      name: dotnet-app
      path: ${{env.DOTNET_ROOT}}/myapp

deploy:
runs-on: windows-latest
needs: build
permissions:
id-token: write
contents: read

steps:
  - name: Download artifact
    uses: actions/download-artifact@v4
    with:
      name: dotnet-app
      path: .

  - name: Login to Azure
    uses: azure/login@v2
    with:
      client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_56EF171E75E444769347DFE4C8BB2D2E }}
      tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E3CF8CDBEFFF4E0A8BC6B39E48DC50B5 }}
      subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_288D6555AD0A4CE58A1F4F087DE566B9 }}

  - name: Deploy to Azure Web App
    id: deploy-to-webapp
    uses: azure/webapps-deploy@v3
    with:
      app-name: 'YourStreet'
      slot-name: 'Production'
      package: .



          
